#!/bin/sh -eu
exec >&2

systemctl --user import-environment \
    DISPLAY \
    XAUTHORITY \
    XDG_SEAT_PATH \
    XDG_SEAT \
    XDG_SESSION_CLASS \
    XDG_SESSION_DESKTOP \
    XDG_SESSION_ID \
    XDG_SESSION_PATH \
    XDG_SESSION_TYPE \
    XDG_VTNR

exec systemctl --user start --wait desktop.target
